### ISSUE TITLE
dev-python/* tests tracker

### ISSUE THREAD

**Issue by Alessandro-Barbieri** [gentoo/guru#1]
```
- no tests available
O tests working
x tests fails
? unknown tests status
```

| Package       | py3.6     | py3.7     |
| :------------- | :----------: | -----------: |
| aspectlib | O | - |
| atomiclong | O | O |
| autoflake | O | O |
| backrefs | O | O |
| black | O | O |
| bracex | O | O |
| curio | O | O |
| dataclasses | O | - |
| hstspreload | - | - |
| httpcore | x | x |
| httptools | - | - |
| httpx | O | O |
| hunter | O | - |
| manhole | O | - |
| mkautodoc | O | O |
| mkdocs-git-revision-date-localized-plugin | O | - |
| mkdocs-material | - | - |
| mkdocs_pymdownx_material_extras | - | - |
| outcome | O | O |
| pygaljs | O | O |
| pymdown-extensions | O | O |
| pymdown-lexers | - | - |
| pyspelling | O | O |
| pytest-benchmark | x | - |
| pytest-instafail | O | O |
| pytest-ordering | ? | ? |
| pytest-sanic | - | - |
| pytest-subtests | O | O |
| pytest-sugar | O | O |
| pytest-travis-fold | O | O |
| pytest-trio | O | O |
| sanic  | x | x |
| sniffio | x | x |
| sphinx-autodoc-typehints | O | O |
| sphinxcontrib-trio | x | x |
| sphobjinv | ? | ? |
| stdio-mgr | O | O |
| timeout-decorator | - | - |
| trio-asyncio | x | x |
| trio | O | O |
| uvicorn | O | O |
| wcmatch | O | O |
|  webpy | O | O |

**Comment by AndrewAmmerlaan** [comment]
> pytest-instafail | O | O

I get: [build.log](https://github.com/gentoo/guru/files/4407811/build.log) on pytest-instafail

Probably there is a dependency missing somewhere, but I'm not sure which one it is.

**Comment by Alessandro-Barbieri** [comment]
What happens if you try with pytest-4*?

**Comment by AndrewAmmerlaan** [comment]
> What happens if you try with pytest-4*?

I get this with pytest-3* and pytest-4*: 
[build.log](https://github.com/gentoo/guru/files/4408090/build.log)

**Comment by Alessandro-Barbieri** [comment]
Which version of pexpect do you have?

**Comment by AndrewAmmerlaan** [comment]
> Which version of pexpect do you have?

4.6.0

**Comment by Alessandro-Barbieri** [comment]
On my machine it loads these plugins:
Instafail
Benchmark
cov
Aspectlib
Catchlog
Asyncio
Forked
Xdist

**Comment by Alessandro-Barbieri** [comment]
It needs itself, try emerging pytest-instafail without testing it and then re emerging with test

**Comment by AndrewAmmerlaan** [comment]
> It needs itself, try emerging pytest-instafail without testing it and then re emerging with test

that did it :+1: 

I'll add itself to the test dependencies

**Comment by Alessandro-Barbieri** [comment]
I see the end of the tunnel

**Comment by AndrewAmmerlaan** [comment]
> mkdocs-git-revision-date-localized-plugin | x | --- | -- | --

This one should be working as of https://gitweb.gentoo.org/repo/proj/guru.git/commit/?h=dev&id=ca75aaa50081da5d3b08be416d08ba835639c82c
