### ISSUE TITLE
dependencies not really needed

### ISSUE THREAD

**Issue by Alessandro-Barbieri** [gentoo/guru#11]
Usually these dependencies aren't useful, please do not add them as package dependencies.
- dev-python/black
- dev-python/check-manifest
- dev-python/coverage
- dev-python/docutils
- dev-python/flake8
- dev-python/isort
- dev-python/mypy
- dev-python/multilint
- dev-python/pep8
- dev-python/pycodestyle
- dev-python/pytest-cov
- dev-python/pytest-runner
- dev-python/readme_renderer
- dev-python/tox
- dev-python/twine

**Comment by ZeroPointEnergy** [comment]
It's not really clear what package this is about. Also the maintainer of the package will probably not get notified if you don't file the issue on bugzilla.
