### ISSUE TITLE
Why isn't dev the default branch?

### ISSUE THREAD

**Issue by Bobbbay** [gentoo/guru#18]
Just stumbled upon this, looks amazing! One thing immediately came into my mind though, why isn't `dev` the default branch, especially since people are asked to clone dev when developing. 

Short question, and cheers!

**Comment by mgorny** [comment]
Because `dev` is unreviewed. Using it comes with a risk that some malicious person may commit something horrible, and our users would get it before we noticed.

**Comment by Bobbbay** [comment]
Ah, that clears it up. Commits to master are pre-thoroughly reviewed, while dev is not. Makes more sense!
