### ISSUE TITLE
Bump sys-block/systemd-swap

### ISSUE THREAD

**Issue by TheEvilSkeleton** [gentoo/guru#20]
`sys-block/systemd-swap` is very outdated. [The latest version is 4.4.0](https://github.com/Nefelim4ag/systemd-swap/releases/tag/4.4.0), and since the ebuild also have the code to search for bleeding edge, you can also add `*-9999`.

**Comment by AndrewAmmerlaan** [comment]
Hi,

The packages in ::guru are community maintained, meaning that you can always bump an outdated ebuild yourself.
See also: https://wiki.gentoo.org/wiki/Project:GURU
