### ISSUE TITLE
dev-vcs/gitqlient: broken build process after update to Qt-5.15.1

### ISSUE THREAD

**Issue by band-a-prend** [gentoo/guru#22]
Just next day after I tested `dev-vcs/gitqlient` ebuilds and pushed it to `dev` branch I update my system from Qt-5.14.2 to stabilized Qt-5.15.1 (i.e. qtnetwork, qtcore with SLOT 0/5.15.1).

After build process become affected to issue https://bugs.gentoo.org/652650 "dev-qt/qtnetwork-5.9.4 with dev-qt/qtcore-5.9.4 - macro redefinition of QT_LINKED_OPENSSL in /usr/include/qt5/Gentoo/gentoo-qconfig.h differs from definition in /usr/include/qt5/QtNetwork/qtnetwork-config.h". So currently build process fails due to using `-Werror` compiler option in GitQlient.pro script.

The current workaround I see is commented the `-Werror` compiler flag within build script.

**Comment by band-a-prend** [comment]
As I can see the removing of `-Werror` flag is common practice for ebuilds from main portage tree.

**Comment by juippis** [comment]
Yes, because it's such a fragile flag on source-based environments.
https://devmanual.gentoo.org/ebuild-writing/common-mistakes/index.html#-werror-compiler-flag-not-removed

-Werror is really good in development, but shouldn't be used with releases overall.

**Comment by band-a-prend** [comment]
Thank you for the link. Fixed without rev-bump in `dev` branch.
