### ISSUE TITLE
move sci-libs/kissfft to ::gentoo

### ISSUE THREAD

**Issue by Alessandro-Barbieri** [gentoo/guru#23]
It's needed by `sci-libs/vtk[all-modules]`

**Comment by Alessandro-Barbieri** [comment]
@stkw0 would you open a PR and maintain it in gentoo?

**Comment by stkw0** [comment]
Yeah, no problem. Give me a day or two

**Comment by stkw0** [comment]
Seems I will be unable to do it since dec 22 because of the covid19.  If someone want to move it to ::gentoo before, feel free to do it
