### ISSUE TITLE
help in naming an ebuild

### ISSUE THREAD

**Issue by Alessandro-Barbieri** [gentoo/guru#25]
I want to package this https://pypi.org/project/pytest-celery/0.0.0a1/ but the version `0.0.0a1` is not allowed in portage. What would you suggest?

**Comment by telans** [comment]
You use `pytest-celery-0.0.0_alpha1` right?

**Comment by Alessandro-Barbieri** [comment]
It's still invalid

**Comment by telans** [comment]
Is there an error or something?

It seems okay according to https://devmanual.gentoo.org/ebuild-writing/file-format/index.html

**Comment by Alessandro-Barbieri** [comment]
Repoman complains about it and so I can't commit

**Comment by telans** [comment]
You could post the exact error you know

**Comment by Alessandro-Barbieri** [comment]
`0.0.0_alpha1` worked, I made another mistake instead
