### ISSUE TITLE
sys-cluster/pcs patch not working

### ISSUE THREAD

**Issue by Alessandro-Barbieri** [gentoo/guru#26]
The [patch](https://github.com/gentoo/guru/blob/master/sys-cluster/pcs/files/openrc-0.10.7.patch) doesn't work for now.
The patch is needed to replace `chkconfig` commands to commands usable on gentoo (`rc-update` and `rc-status`).
The problem is that they have different outputs to parse

**Comment by custom82** [comment]
and rc-service

**Comment by Alessandro-Barbieri** [comment]
I think we need to split the commands like this
`cmd = ['/usr/bin/rc-config','list',' default','|','/bin/grep','-q', service]`
