### ISSUE TITLE
mkdocs-material move to ::gentoo progress tracker

### ISSUE THREAD

**Issue by AndrewAmmerlaan** [gentoo/guru#3]
mkdocs-material is a very popular mkdocs theme. According to GitHub statistics 39% of the total packages using mkdocs use this theme. Therefore it seems to me that it would be a good idea to have this theme available in ::gentoo. There are some additional dependencies required by mkdocs-material, and I've opened up this tracker to keep track of them all:

mkdocs-material:
-  dev-python/mkdocs-minify-plugin  (no doc or test, ready to merge)
-  dev-python/pymdown-extensions (test working, doc fails)
    - dev-python/mkdocs-git-revision-date-localized-plugin (tests work, no doc)
    - dev-python/pymdown-lexers (no doc or test, all good)
    - dev-python/pyspelling (tests work, doc fails)
       - dev-python/wcmatch (test work, doc fails)
          - dev-python/backrefs (tests work, doc compiles, all good)
          - dev-python/bracex (tests work, doc compiles, all good)
             - dev-python/mkdocs_pymdownx_material_extras (no tests, no doc, all good)

- (docs.eclass: https://github.com/gentoo/gentoo/pull/15232)

I'll try to make small PRs, a couple of packages at the same time. But there are some circular dependencies that I can't avoid. This is where I'll keep track of the progress.

@Alessandro-Barbieri you maintain some of these packages, would you mind if I add myself to the metadata files, and make PRs for these packages?

**Comment by Alessandro-Barbieri** [comment]
OK, do you know if tests are all working?

**Comment by AndrewAmmerlaan** [comment]
> OK, do you know if tests are all working?

Not sure, but I'm testing that at the moment

**Comment by Alessandro-Barbieri** [comment]
From #1 the only one failing are in mkdocs-git-revision-date-localized-plugin

**Comment by AndrewAmmerlaan** [comment]
> From #1 the only one failing are in mkdocs-git-revision-date-localized-plugin

I just fixed that one :smile:

**Comment by AndrewAmmerlaan** [comment]
> OK, do you know if tests are all working?

I still have some packages failing to compile USE="doc" though.

My version bump of mkdocs got merged: https://github.com/gentoo/gentoo/pull/15150
and I tried to enable doc building on those package that need the new version, but I got an error that I couldn't solve (see my commits of today)

**Comment by AndrewAmmerlaan** [comment]
@Alessandro-Barbieri I just went through all of these, and the only obstacle is those packages requiring mkdocs-git-revision-localized-plugin (pymdown-extensions, pyspelling and wcmatch). The packages that require this can only compile docs in the git repo, and give this error when running in emerge:
```
ERROR   -  Unable to read git logs of '/var/tmp/portage/dev-python/pymdown-extensions-7.0.0/work/pymdown-extensions-7.0.0/docs/src/markdown/index.md'. To ignore this error, set option 'ignoring_missing_git: true'
ERROR   -  Error reading page 'index.md': Cmd('git') failed due to: exit code(128)
```

It says to set this option `ignoring_missing_git: true` but putting it in mkdocs.yml just gives me an unrecognised option error. Any ideas on how to fix this maybe?

@juippis would it be possible to merge pymdown-extensions, pyspelling and wcmatch without USE="doc" support? It seems non-trivial to fix this to work outside of the git repo.

**Comment by juippis** [comment]
That looks really weird, I don't think it's worth doing the `git` steps just to get documentation built. 

Looking at their Github, 
https://github.com/facelessuser/pymdown-extensions
it doesn't look like it has to be that complex? Can you paste the ebuild here?

**Comment by AndrewAmmerlaan** [comment]
> That looks really weird, I don't think it's worth doing the `git` steps just to get documentation built.
> 
> Looking at their Github,
> https://github.com/facelessuser/pymdown-extensions
> it doesn't look like it has to be that complex? Can you paste the ebuild here?

```
# Copyright 1999-2020 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

EAPI=7

PYTHON_COMPAT=( python3_{6,7,8} )

DOCBUILDER="mkdocs"
DOCDEPEND="
	dev-python/mkdocs-minify-plugin
	dev-python/mkdocs-git-revision-date-localized-plugin
	dev-python/mkdocs-material
	dev-python/pymdown-lexers
	dev-python/pyspelling
"

inherit distutils-r1 docs

DESCRIPTION="Extensions for Python Markdown."
HOMEPAGE="
	https://github.com/facelessuser/pymdown-extensions
	https://pypi.org/project/pymdown-extensions
"
SRC_URI="https://github.com/facelessuser/${PN}/archive/${PV}.tar.gz -> ${P}.tar.gz"

LICENSE="MIT"
SLOT="0"
KEYWORDS="~amd64 ~x86"

RDEPEND=">=dev-python/markdown-3.2[${PYTHON_USEDEP}]"

DEPEND="test? (
		dev-python/pyyaml[${PYTHON_USEDEP}]
)"

distutils_enable_tests pytest

python_prepare_all() {
	# git revision date plugin needs git repo to build
	if use doc; then
		git init || die
		git add -A || die
		git commit -q -m ".." || die
	fi
	distutils-r1_python_prepare_all
}
```

They are also in ::guru (with the workaround)

Maybe another way to fix it would be to set this option as the error message suggests: `To ignore this error, set option 'ignoring_missing_git: true'` but I got unrecognised option when I tried. and google wasn't very helpful when I searched for this option.

**Comment by juippis** [comment]
So I just removed 
```
plugins:
  - search
  - git-revision-date-localized
  - minify:
      minify_html: true
```
from *mkdocs.yml* and called `python3 -m mkdocs build --verbose` which then made me a beatiful browsable HTML documents under *site/* directory.

**Comment by Alessandro-Barbieri** [comment]
new version https://github.com/squidfunk/mkdocs-material/releases/tag/5.0.2

**Comment by AndrewAmmerlaan** [comment]
> So I just removed
> 
> ```
> plugins:
>   - search
>   - git-revision-date-localized
>   - minify:
>       minify_html: true
> ```
> 
> from _mkdocs.yml_ and called `python3 -m mkdocs build --verbose` which then made me a beatiful browsable HTML documents under _site/_ directory.

Awesome, this is a way better solution, thanks!
I just pushed this to guru, all packages appear to be fine now, so I'll make a PR for them soon.

**Comment by AndrewAmmerlaan** [comment]
Just made two PRs for this. Most of it had to go in one because some deps of mkdocs-material depend on mkdocs-material to compile their documentation.
https://github.com/gentoo/gentoo/pull/15302
https://github.com/gentoo/gentoo/pull/15286 (has to be merged first)

@juippis could you please take a look at these. They have been in guru for sometime and received several fixes, so I think they should be mostly fine. Docs and tests are all working for me.
