### ISSUE TITLE
net-misc/freetube-bin-0.12.0 build fail

### ISSUE THREAD

**Issue by autopr3z** [gentoo/guru#50]
I'm having trouble emerging this package, and the output isn't telling me much. I can provide whatever information is needed, in addition to below:

- [emerge --info](https://dpaste.com/8A5EUSK4X)
- [build log](https://dpaste.com/AEJABBE63)

Is it an issue on my end?

**Comment by r7l** [comment]
It's not just you. Upstream changed the icon from multiple PNG files to a single SVG. I am having the same issue. 

These lines seem to break the ebuild now:

https://github.com/gentoo/guru/blob/ecffeb2cb01e88d123ad237164d8f33b4b9392d2/net-misc/freetube-bin/freetube-bin-0.12.0.ebuild#L32-L34

**Comment by autopr3z** [comment]
Fix worked great for me. Thanks!
