### ISSUE TITLE
[media-gfx/akira-0.0.13] dosym: two arguments needed

### ISSUE THREAD

**Issue by Dr-Terrible** [gentoo/guru#54]
The ebuild for akira v0.0.13 fails during the installation phase:

```sh
>>> Source compiled.
>>> Test phase [not enabled]: media-gfx/akira-0.0.13

>>> Install media-gfx/akira-0.0.13 into /var/tmp/portage/media-gfx/akira-0.0.13/image
/var/tmp/portage/media-gfx/akira-0.0.13/temp/environment: line 2344: meson_src_isntall: command not found
 * ERROR: media-gfx/akira-0.0.13::guru failed (install phase):
 *   dosym: two arguments needed
 * 
 * If you need support, post the output of `emerge --info '=media-gfx/akira-0.0.13::guru'`,
 * the complete build log and the output of `emerge -pqv '=media-gfx/akira-0.0.13::guru'`.
 * The complete build log is located at '/var/log/portage/media-gfx:akira-0.0.13:20210415-122745.log'.
 * For convenience, a symlink to the build log is located at '/var/tmp/portage/media-gfx/akira-0.0.13/temp/build.log'.
 * The ebuild environment file is located at '/var/tmp/portage/media-gfx/akira-0.0.13/temp/environment'.
 * Working directory: '/var/tmp/portage/media-gfx/akira-0.0.13/work/Akira-0.0.13'
 * S: '/var/tmp/portage/media-gfx/akira-0.0.13/work/Akira-0.0.13'
 * QA Notice: command not found:
 * 
 * 	/var/tmp/portage/media-gfx/akira-0.0.13/temp/environment: line 2344: meson_src_isntall: command not found

>>> Failed to emerge media-gfx/akira-0.0.13, Log file:

>>>  '/var/log/portage/media-gfx:akira-0.0.13:20210415-122745.log'
```

Clearly, this ebuild has not been properly tested before to be committed to the overlay.

**Comment by queereen** [comment]
There's a typo in `src_install()`, but also `x11-libs/goocanvas` is outdated, so it won't compile.

**Comment by queereen** [comment]
Pushed fix, but someone needs to bump `x11-libs/goocanvas` on main gentoo repo.

**Comment by AndrewAmmerlaan** [comment]
`-r` is not a valid argument for `dosym` AFAIK, it just requires two arguments, the target and the name of the link.

**Comment by AndrewAmmerlaan** [comment]
The dependency on x11-libs/goocanvas:3 broke the dependency resolution, I have removed the keywords until a solution is found.

**Comment by queereen** [comment]
[dosym8 does](https://devmanual.gentoo.org/eclass-reference/eapi8-dosym.eclass/index.html) - i guess i should use EAPI=8

**Comment by queereen** [comment]
> The dependency on `x11-libs/goocanvas:3` broke the dependency resolution, I have removed the keywords until a solution is found.

made ticket on bugzilla

**Comment by telans** [comment]
> [dosym8 does](https://devmanual.gentoo.org/eclass-reference/eapi8-dosym.eclass/index.html) - i guess i should use EAPI=8

inherit eapi8-dosym

**Comment by queereen** [comment]
> > [dosym8 does](https://devmanual.gentoo.org/eclass-reference/eapi8-dosym.eclass/index.html) - i guess i should use EAPI=8
> 
> inherit eapi8-dosym

oh, right
