### ISSUE TITLE
geographiclib USE_EXPAND

### ISSUE THREAD

**Issue by Alessandro-Barbieri** [gentoo/guru#6]
I'm trying to get use expand working for geographiclib but after many tries I'll seek for advice. What am I doing wrong?

**Comment by juippis** [comment]
Can you show your ebuild where you're having it? 

Also generally we try NOT to use these. They are most often awful to maintain, and awful user experience too. (I think it's acceptable with specific rdeps in mind)

**Comment by Alessandro-Barbieri** [comment]
The ebuild is already here https://github.com/gentoo/guru/blob/master/sci-geosciences/geographiclib/geographiclib-1.50.1.ebuild

**Comment by juippis** [comment]
Without testing out of my memory this should be the syntax: 
```
IUSE_GEOIDS_DATASETS=(
	egm84-30
	egm84-15
	egm96-15
	egm96-5
	egm2008-5
	egm2008-2-5
	egm2008-1
)
IUSE_GRAVITY_MODELS=(
	egm84
	egm96
	egm2008
	wgs84
)
IUSE_MAGNETIC_MODELS=(
	wmm2010
	wmm2015v2
	wmm2020
	igrf11
	igrf12
	emm2010
	emm2015
	emm2017
)
IUSE_PRECISION=(
	arbitrary
	+double
	long-double
	quad
	single
)

IUSE_ALL=(
	${IUSE_GEOIDS_DATASETS[@]/#/geoids_datasets_}
	${IUSE_GRAVITY_MODELS[@]/#/gravity_models_}
	${IUSE_MAGNETIC_MODELS[@]/#/magnetic_models_}
	${IUSE_PRECISION[@]/#/precision_}
)



IUSE="boost doc examples geoids gravity magnetic python ${IUSE_ALL}"
```

Can dig deeper into this tomorrow.

**Comment by Alessandro-Barbieri** [comment]
Basically I copied from the asterisk ebuild

**Comment by AndrewAmmerlaan** [comment]
This has been fixed in https://gitweb.gentoo.org/repo/proj/guru.git/commit/?h=dev by adding `profiles/make.defaults` with `USE_EXPAND="..."`
