### ISSUE TITLE
app-text/komikku dependencies

### ISSUE THREAD

**Issue by KuroLevin** [gentoo/guru#61]
komikku does not depend on dev-python/cloudscraper since version 0.24.0 and requires the dev-lang/python version to be >=3.8 since version 0.28.1 (it is currently possible to install komikku-0.28.1 with python 3.7)

**Comment by Alessandro-Barbieri** [comment]
it's better to open this kind of issues on bugs.gentoo.org

**Comment by Alessandro-Barbieri** [comment]
@KuroLevin are you sure? It imports cloudscraper here https://gitlab.com/valos/Komikku/-/blob/master/komikku/servers/mangakawaii/__init__.py#L8

**Comment by KuroLevin** [comment]
Looks like the dependency was re-added in version 29.2 (commit e010d0b155e118ba55bf2d41e7a928f312620102)
