### ISSUE TITLE
dev-python/cloudscraper is now in the main tree

### ISSUE THREAD

**Issue by vaartis** [gentoo/guru#63]
Since a few days ago, cloudscraper is now [in the main tree](https://packages.gentoo.org/packages/dev-python/cloudscraper). That was done in an effort to bring another package that needs it into the tree too, but since it's now there and old versions quickly become irrelevant due to the nature of the package (that is, old versions break after cloudflare changes things and stop working), perhaps they should be dropped.

cc @xgqt

**Comment by xgqt** [comment]
Yes, sure, thx for informing me.

But you could have done this before adding it to ::guru. 
If you did and I didnt see that - sorry

**Comment by xgqt** [comment]
https://gitweb.gentoo.org/repo/proj/guru.git/commit/?h=dev&id=b2d664f55931344a38c3fbeedc58ebb225ab7992

**Comment by vaartis** [comment]
> 
> 
> Yes, sure, thx for informing me.
> 
> But you could have done this before adding it to ::guru.
> If you did and I didnt see that - sorry

Not sure what you mean by this. I've submitted both packages into the main tree from the start, and just noticed that this one exists here too, so I thought that since it's in the main tree now then there's no need for it here. Didn't even notice it was here until today, that's probably something I should check beforehand.

**Comment by xgqt** [comment]
> > Yes, sure, thx for informing me.
> > But you could have done this before adding it to ::guru.
> > If you did and I didnt see that - sorry
> 
> Not sure what you mean by this. I've submitted both packages into the main tree from the start, and just noticed that this one exists here too, so I thought that since it's in the main tree now then there's no need for it here. Didn't even notice it was here until today, that's probably something I should check beforehand.

Ok, I see.
You are right that you were not obligated to perform those checks.
I assumed you knew of it being in bury beforehand.
