### ISSUE TITLE
 How to properly handle packages that depend on Lua5.3?

### ISSUE THREAD

**Issue by vowstar** [gentoo/guru#7]
I have a ebuild depends on Lua5.3 (It depends on gentoo slotted dev-lang/lua
versions and dependencies.)

https://github.com/gentoo/guru/blob/11f4549a67d2a005f0c5108d4759b152775d54f4/media-video/kikoplay/kikoplay-0.6.0.ebuild
However, Gentoo is using the old 5.1.

See also:
https://bugs.gentoo.org/671248
https://bugs.gentoo.org/657722

According to the above discussion, it should be inclined to use slotted lua. 
I wrote this ebuild as much as possible based on my imagination and understanding, 
But for a slotted lua that has not been completed for many years, is this way correct?

**Comment by juippis** [comment]
Looks like you've depended on it correctly. The problem is that lua:5.3 is masked in Gentoo, and it's an ongoing process getting it unmasked. 

Are you **absolutely** sure it doesn't work with lua-5.1 or with luajit? 

I don't think you have a way around this otherwise.

**Comment by vowstar** [comment]
> Looks like you've depended on it correctly. The problem is that lua:5.3 is masked in Gentoo, and it's an ongoing process getting it unmasked.
> 
> Are you **absolutely** sure it doesn't work with lua-5.1 or with luajit?
> 
> I don't think you have a way around this otherwise.

Yes, I absolutely sure. Even the ``mpv`` linked with ``juajit(only support lua5.1) can cause core dump.
And all the functions of this software referenced in it are from 5.3, using 5.1 (lua:SLOT=0 or lua:SLOT=5.1) will cause unimplemented errors when compile. And the lua scripts using lua 5.3 syntax. It is very strange to port all to 5.1 because 5.3 is the future and on debian/rhel lua 5.3 have no problem.

There are many software depends on lua 5.3, and I unmasked ``lua:5.1 lua:5.2 lua:5.3 eselect-lua`` on my PC, it works well. Some package in Gentoo still depends on ``lua:0``, I guess it better changed to ``lua:5.1`` to apply slotted dev-lang/lua and solve this problem.

**Comment by vowstar** [comment]
This issue fixed because slotted lua unmasked in ::gentoo

https://gitweb.gentoo.org/repo/gentoo.git/tree/profiles/package.mask
https://github.com/gentoo/guru/commit/52b132eb596647d34f0e2d59aaad470971d42e93
