### ISSUE TITLE
Could I unmasked slotted lua in guru profiles/package.unmask to solve package issue?

### ISSUE THREAD

**Issue by vowstar** [gentoo/guru#9]
Recently I have a problem about how to properly handle packages that depend on Lua5.3, this is the discussion: https://github.com/gentoo/guru/issues/7

However, I think this matter needs more discussion and help, because there is some problem with the most recent software package I maintain.

https://github.com/gentoo/guru/commit/3f02df8d445c5e5a9a6c24f6782ff4aadec12475

The main problem is that in ::gentoo the ``dev-lang/lua:5.1 dev-lang/lua:5.2 dev-lang/lua:5.3`` are masked, this is extremely strange and unreasonable, many excellent software which using latest lua  may blocked.

Two years ago, some one tried to fixed the lua sloted problem. gentoo/gentoo#9300
But dev-lua packages must be updated to newer EAPIs to consolidate slotted dev-lang/lua versions.
https://bugs.gentoo.org/671248
To solve this, many works should be done.

In ::gentoo, many package must depend on Lua5.3 now and in future.

```
./app-admin/conky/conky-1.11.5.ebuild:  || ( dev-lang/lua:5.3 dev-lang/lua:5.2 )
./net-proxy/haproxy/haproxy-1.9.14.ebuild:      lua? ( dev-lang/lua:5.3 )
./net-proxy/haproxy/haproxy-2.0.9999.ebuild:    lua? ( dev-lang/lua:5.3 )
./net-proxy/haproxy/haproxy-2.0.14.ebuild:      lua? ( dev-lang/lua:5.3 )
./net-proxy/haproxy/haproxy-1.9.9999.ebuild:    lua? ( dev-lang/lua:5.3 )
./net-proxy/haproxy/haproxy-2.0.13.ebuild:      lua? ( dev-lang/lua:5.3 )
./net-proxy/haproxy/haproxy-2.1.3.ebuild:       lua? ( dev-lang/lua:5.3 )
./net-proxy/haproxy/haproxy-2.1.9999.ebuild:    lua? ( dev-lang/lua:5.3 )
./net-proxy/haproxy/haproxy-1.8.13.ebuild:      lua? ( dev-lang/lua:5.3 )
./net-proxy/haproxy/haproxy-1.8.9.ebuild:       lua? ( dev-lang/lua:5.3 )
./net-proxy/haproxy/haproxy-1.8.25.ebuild:      lua? ( dev-lang/lua:5.3 )
./net-proxy/haproxy/haproxy-2.1.4.ebuild:       lua? ( dev-lang/lua:5.3 )
./net-proxy/haproxy/haproxy-1.9.15.ebuild:      lua? ( dev-lang/lua:5.3 )
./net-proxy/haproxy/haproxy-1.8.24.ebuild:      lua? ( dev-lang/lua:5.3 )
./dev-db/redis/redis-4.0.14.ebuild:     if false && has_version 'dev-lang/lua:5.3'; then
./dev-db/redis/redis-5.0.8.ebuild:      if false && has_version 'dev-lang/lua:5.3'; then
./dev-db/redis/redis-5.0.5.ebuild:      if false && has_version 'dev-lang/lua:5.3'; then
./dev-db/redis/redis-5.0.7.ebuild:      if false && has_version 'dev-lang/lua:5.3'; then
./sys-apps/likwid/likwid-4.3.4.ebuild:  dev-lang/lua:5.3"
./sys-apps/likwid/likwid-4.3.3.ebuild:  dev-lang/lua:5.3"
```

https://bugs.gentoo.org/657722
According to the above discussion, it should be inclined to use slotted lua.

So there better have a rule about how to deal with the packages depend on lua:5.3, lua:5.2 or lua:5.1.
I think the packages in ::gentoo depend on lua:0 should be changed to || ( dev-lang/lua:0 dev-lang/lua:5.1 ) and lua:5.3, lua:5.2, lua:5.1 and eselect-lua shoud be unmasked.

Just like gentoo/lua project : https://github.com/gentoo/lua/blob/master/profiles/package.unmask
It unmasked these package below
```
dev-lang/lua:5.1
dev-lang/lua:5.2
dev-lang/lua:5.3
app-eselect/eselect-lua
virtual/lua
```

In this discussion, https://github.com/gentoo/guru/commit/3f02df8d445c5e5a9a6c24f6782ff4aadec12475, the package is Kikoplay. This package I test it by hand under gnome desktop environment with slotted lua unmasked and works well.

About this disscussion, I have some questions to ask for help:

- Could I unmasked slotted lua in profiles/package.unmask at ``guru/profiles/package.unmask`` ?
- Can I add package which depends on slotted lua (such as `` lua:5.3, lua:5.2, lua:5.1 ``) in guru project?

There is another unrelated question:

- Package can't commited to guru if it is already exist in ::gentoo, but if a package is too old in  ::gentoo and nobody version bump it, could we push latest version of package to gentoo (to solve this problem  https://bugs.gentoo.org/715658 https://github.com/gentoo/guru/commit/298e7c44e65c2315468e871b1e5a63c039a52e9b )?

**Comment by AndrewAmmerlaan** [comment]
> About this disscussion, I have some questions to ask for help:
> 
>     * Could I unmasked slotted lua in profiles/package.unmask at `guru/profiles/package.unmask` ?

Presumably there is a reason it is masked in ::gentoo, do you know what the reason is? Are there any issues with the slotted lua ebuilds?
 
>     * Can I add package which depends on slotted lua (such as `lua:5.3, lua:5.2, lua:5.1`) in guru project?

If you ask me, I'd say yes. (As there is confusion about this, I think we should discuss this and add a entry to the FAQ about it when we have decided what to do)

> There is another unrelated question:
> 
>     * Package can't commited to guru if it is already exist in ::gentoo, but if a package is too old in  ::gentoo and nobody version bump it, could we push latest version of package to gentoo (to solve this problem  https://bugs.gentoo.org/715658 [298e7c4](https://github.com/gentoo/guru/commit/298e7c44e65c2315468e871b1e5a63c039a52e9b) )?

I understand the frustration with too-old-packages in ::gentoo, especially if you want to make an ebuild that depends on a newer version of the package in question. However, guru is meant as an extension to ::gentoo, and as such should not contain package overrides. Proxy-maint is the place to push updates to packages in :;gentoo. 

That being said, we could have the discussion of allowing packages that are in :;gentoo into ::guru provided they are under a different name (e.g foo-guru.ebuild). Personally, I'm not fond of this idea at all, as thing are likely to get messy. But it is a discussion we could have I suppose.

**Comment by mgorny** [comment]
> * Could I unmasked slotted lua in profiles/package.unmask at `guru/profiles/package.unmask` ?

No, you can't. By definition adding guru must not affect packages from ::gentoo.

**Comment by Alessandro-Barbieri** [comment]
Will kikoplay be accepted in the Lua overlay?
So we can unmask, remove it from here and close the issue

**Comment by vowstar** [comment]
> Will kikoplay be accepted in the Lua overlay?
> So we can unmask, remove it from here and close the issue

Lua overlay is for lua only development, kikoplay can't put there.

**Comment by vowstar** [comment]
@AndrewAmmerlaan 
> Do you know what the reason is?

The reason is for testing slotted lua by one of a developer in 2014. 

"it was rediculous back in 2014"

```text
# Matti Bickel <mabi@gentoo.org> (22 Apr 2014)
# Masked slotted lua for testing
# William Hubbs <williamh@gentoo.org> (07 Aug 2016)
# Taking this mask since Mabi is retired
# Rafael Martins <rafaelmartins@gentoo.org> (04 Dec 2016)
# Adding Lua 5.3 to mask
app-eselect/eselect-lua
=dev-lang/lua-5.1.5-r100
=dev-lang/lua-5.1.5-r101
=dev-lang/lua-5.2.3
=dev-lang/lua-5.2.3-r1
=dev-lang/lua-5.2.3-r2
=dev-lang/lua-5.3.3
=dev-lang/lua-5.3.3-r1
```

> Are there any issues with the slotted lua ebuilds?

Many package with packages in ::gentoo depend on`` lua:0`` should be changed to ``|| ( dev-lang/lua:0 dev-lang/lua:5.1`` ), and ``lua:5.3, lua:5.2, lua:5.1 eselect-lua shoud be unmasked``. 
A lot of testing works todo.
With gentoo/proxy-maint, may be difficult to implement due to time issues and very slow.

**Comment by vowstar** [comment]
Now lua 5.4 has been released, for the development of gentoo, we should find a way to solve this problem instead of blindly evading.

**Comment by AndrewAmmerlaan** [comment]
> Now lua 5.4 has been released, for the development of gentoo, we should find a way to solve this problem instead of blindly evading.

I agree, this problem should be fixed at it's root. Either the slotted lua ebuilds should be fixed and unmasked, or the 0 slot should also have new ebuilds. At the very least we could make a Pull Request to update the lua version in slot 0. If you need any help, I'd be happy to look into it, though I'm not familiar with lua.

**Comment by vowstar** [comment]
@AndrewAmmerlaan Thank you very much!

The main difficulty I am currently facing is that many stable software still depends on ``lua: 0``, however ``lua: 0`` is equivalent to ``lua: 5.1``.

The real situation of these software that depends on`` lua: 0`` is to depend on ``lua-5.1.5``, but ``lua-5.1.5`` is very different from ``lua-5.2`` and ``lua-5.3`` respectively. 

Almost all scripts of different lua are incompatible, just like Python encountered the same situation.

However, some software started to update lua to ``5.2`` or ``5.3``, and even some new software started to use ``lua 5.4``, and the lua scripts between them were not compatible with each other. 

So it is quite difficult to update ``lua: 0`` directly.
May be slotted lua is the final solution, such as python.

**Comment by AndrewAmmerlaan** [comment]
> May be slotted lua is the final solution, such as python.

Do all packages that depend on lua have `DEPEND="dev-lang/lua:0"`, or are there also packages which are missing the slot (e.g. `DEPEND="dev-lang/lua"`)? If there are still packages that are missing the slot information in their DEPEND variables that should be fixed first, otherwise removing the mask would break these packages.

> Many package with packages in ::gentoo depend on lua:0 should be changed to || ( dev-lang/lua:0 dev-lang/lua:5.1 )

This should be relatively easy, provided the slotted ebuilds have equivalent keywords and use flags.

**Comment by vowstar** [comment]
>  Are there also packages which are missing the slot (e.g. DEPEND="dev-lang/lua")

In ::gentoo, there are 163 packages are missing the lua slot, and 313 packages depends on lua. some package using luajit to workaround lua problem. luajit sometimes can replace lua 5.1 or 5.2(with lua52compat, you know it may cause compatibility problems).

| Ebuilds depends on lua | Count |
| ---------------------- | ----- |
| Missing slot           | 163   |
| Total                  | 313   |

**Comment by AndrewAmmerlaan** [comment]
> In ::gentoo, there are 163 packages are missing the lua slot

Oooh, that is a lot :disappointed: 

That does explain the mask though, unmasking it will give problems with all these packages.
What should we do? We can't make Pull Requests for 163 packages, it is too much.

**Comment by vowstar** [comment]
Yes, the related packages are too much to give a pull request via gentoo/proxy-maint.

**Comment by vowstar** [comment]
@mgorny @juippis In ::gentoo many stable software still depends on ``lua:0``, however ``lua:0`` is equivalent to ``lua:5.1``. The real situation of these software that depends on ``lua:0`` is to depend on lua-5.1.5, but lua-5.1.5 is very different from lua-5.2 and lua-5.3 respectively. *Almost* all scripts between different lua version (e.g.:``lua:5.1`` and ``lua:5.3``) are incompatible, just like ``python:2.7`` and ``python:3.6`` encountered the same situation. So it is quite difficult to update ``lua:0`` directly because it will broad affecting a lot of packages and caused bugs. Many package with packages in ::gentoo depend on ``lua:0`` should be changed to ``|| ( dev-lang/lua:0 dev-lang/lua:5.1 )`` to keep 
backward compatible.
How ever in ::gentoo there are 163 packages are missing the lua slot, and 313 packages depends on lua. What should we do to solve this problem? Could we make many commit (163) in a pull request to ::gentoo try to fix this problem?
The plan is:
- [ ] 163 commit to changed the ebuild which are depend on ``lua`` and missing the lua slot to ``|| ( dev-lang/lua:0 dev-lang/lua:5.1 )`` to avoid bug when unmask new newer lua version.
- [ ] changed the packages (many) depend on ``lua:0`` to ``|| ( dev-lang/lua:0 dev-lang/lua:5.1 )``  to keep backward compatible.
- [ ] Check for possible conflicts between lua and luajit, maybe a lot of package should be adjusted.
- [ ] unmask ``lua:5.1 lua:5.2 lua:5.3 eselect-lua`` to solve this problem finally.

**Comment by juippis** [comment]
I don't have time to go through all the backlog right now (I'll get back to this and other GURU things soon), but the lua project in Gentoo is working actively to make some sense into lua. Please communicate with them to know more about their plans and what you can do to help.
https://wiki.gentoo.org/wiki/Project:Lua

**Comment by vowstar** [comment]
@juippis 
Thank you for your reply

**Comment by AndrewAmmerlaan** [comment]
> || ( dev-lang/lua:0 dev-lang/lua:5.1 )

What bout doing `|| ( <dev-lang/lua-5.2:0 dev-lang/lua:5.1 )` on the packages that require 5.1 instead, this will allow you to add newer ebuilds to the 0 slot as well. The slotted ebuild is of course the nicest solution, but in case that doesn't work out doing it like this allows you to revert to pushing a newer version to the 0 slot.

**Comment by vowstar** [comment]
``|| ( <dev-lang/lua-5.2:0 dev-lang/lua:5.1 )``
Awesome solution

**Comment by lanodan** [comment]
I think we could slotmove `dev-lang/lua:0` to `:5.1` or just consider that `:0` is stuck to 5.1.x.

Which means basically no ``|| ()`` in packages, which is also what `::lua` seems to be doing, otherwise we're going to have something literally like `PYTHON_COMPAT` but for lua and I don't think we require something this complicated.

**Comment by vowstar** [comment]
> I think we could slotmove dev-lang/lua:0 to :5.1 in gentoo or just consider that :0 is stuck to 5.1.x.

@lanodan This may be the best clean solution. However, we need developer's help to unmask ``5.1.x`` and slotmove.

**Comment by lanodan** [comment]
[2020-05-02 21:34:01-0700] Rui Huang:
> > I think we could slotmove dev-lang/lua:0 to :5.1 in gentoo or just consider that :0 is stuck to 5.1.x.
> 
> @lanodan This may be the best clean solution. However, we need developer's help to unmask ``5.1.x`` and slotmove.

Doing this change probably isn't much of an adventure, just needs a response back from the Lua Project. You need to unmask >=5.2.0 anyway.

**Comment by AndrewAmmerlaan** [comment]
> I think we could slotmove dev-lang/lua:0 to :5.1 in gentoo or just consider that :0 is stuck to 5.1.x.

As I understand it, some lua packages DEPEND on `dev-lang/lua` without slot, the slot information should be added to these packages before unmasking the slotted lua ebuilds. So just a slotmove would not be enough, right?

**Comment by Alessandro-Barbieri** [comment]
I think that discussing here is a waste of time, you should involve the Lua team, maybe send an email on gentoo-dev ML.

**Comment by vowstar** [comment]
Email already send but no response from developer

**Comment by mgorny** [comment]
Last I checked, the primary problem was lack of any mechanism to choose Lua version from packages. Maintainers were more focused about discussing static vs shared linking than solving real problems. I'm not aware of anyone starting to write the needed eclass.

**Comment by AndrewAmmerlaan** [comment]
> Recently I have a problem about how to properly handle packages that depend on Lua5.3, this is the discussion: #7
> 
> However, I think this matter needs more discussion and help, because there is some problem with the most recent software package I maintain.
> 
> [3f02df8](https://github.com/gentoo/guru/commit/3f02df8d445c5e5a9a6c24f6782ff4aadec12475)
> 
> The main problem is that in ::gentoo the `dev-lang/lua:5.1 dev-lang/lua:5.2 dev-lang/lua:5.3` are masked, this is extremely strange and unreasonable, many excellent software which using latest lua may blocked.
> 
> Two years ago, some one tried to fixed the lua sloted problem. [gentoo/gentoo#9300](https://github.com/gentoo/gentoo/pull/9300)
> But dev-lua packages must be updated to newer EAPIs to consolidate slotted dev-lang/lua versions.
> https://bugs.gentoo.org/671248
> To solve this, many works should be done.

@vowstar a lua.eclass has just been merged to ::gentoo https://github.com/gentoo/gentoo/commit/4e00818e9a213697430e548a86e7936f83543ba9

Hopefully it will solve your problem

**Comment by vowstar** [comment]
@AndrewAmmerlaan Nice!

**Comment by vowstar** [comment]
This issue fixed because slotted lua unmasked in ::gentoo

https://gitweb.gentoo.org/repo/gentoo.git/tree/profiles/package.mask
https://github.com/gentoo/guru/commit/52b132eb596647d34f0e2d59aaad470971d42e93
